---
- name: Install cloudbase-init
  ansible.windows.win_package:
    path: '{{ cloudbase_msi_url }}'
    product_id: cloudbase-init
    arguments: /qn /l*v cloudbase_install_log.txt
    state: present

- name: Configure cloudbase-init.conf file
  ansible.windows.win_template:
    src: cloudbase-init.conf.j2
    dest: '{{ cloudbase_install_path }}cloudbase-init.conf'
    newline_sequence: '\n'
    backup: true

- name: Configure cloudbase-init-unattended.conf file
  ansible.windows.win_template:
    src: cloudbase-init-unattend.conf.j2
    dest: '{{ cloudbase_install_path }}cloudbase-init-unattend.conf'
    newline_sequence: '\n'
    backup: true
