---
- name: Install cloudbase-init
  ansible.windows.win_package:
    path: https://cloudbase.it/downloads/CloudbaseInitSetup_Stable_x64.msi
    product_id: cloudbase-init
    arguments: /qn /l*v cloudbase_install_log.txt
    state: present

- name: Configure cloudbase-init.conf file
  ansible.windows.win_template:
    src: cloudbase-init.conf.j2
    dest: '{{ cloudbase_install_path }}cloudbase-init.conf'
    newline_sequence: '\n'
    backup: yes

- name: Configure cloudbase-init-unattended.conf file
  ansible.windows.win_template:
    src: cloudbase-init-unattend.conf.j2
    dest: '{{ cloudbase_install_path }}cloudbase-init-unattend.conf'
    newline_sequence: '\n'
    backup: yes